version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      worker-rs:
        patterns:
          - worker
          - worker-macros

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      wrangler:
        patterns:
          - wrangler

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly